#! /bin/sh
$HOME/.config/polybar/launch.sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
conky &
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) export SSH_AUTH_SOCK
nitrogen --restore &
picom --vsync --no-fading-openclose --clear-shadow &
setxkbmap en &
xrandr --output HDMI-0 --mode 3440x1440 --rate 100
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config split_ratio          0.5
bspc config window_gap           8

bspc rule -a Microsoft-edge desktop='^4'

sleep 1 && pkill -USR1 -x sxhkd || /usr/bin/sxhkd &
